dest_path: /reports
input_path: /repos
listen_address: 0.0.0.0:50054
timeout: 100
compilation:
  Dapp-Learning:
    prepare:
      - "npm install @openzeppelin/contracts"
    compilation_base:
      remap:
        "@openzeppelin": ./node_modules/@openzeppelin
      allow_paths:
        - node_module/@openzeppelin


