// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/analyzer/reporter.proto

package analyzer // import "protobuf/analyzer"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AnalysisRequest struct {
	BeforeChange         *AnalysisTarget `protobuf:"bytes,1,opt,name=before_change,json=beforeChange,proto3" json:"before_change,omitempty"`
	AfterChange          *AnalysisTarget `protobuf:"bytes,2,opt,name=after_change,json=afterChange,proto3" json:"after_change,omitempty"`
	DiffsLogPath         string          `protobuf:"bytes,3,opt,name=diffs_log_path,json=diffsLogPath,proto3" json:"diffs_log_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AnalysisRequest) Reset()         { *m = AnalysisRequest{} }
func (m *AnalysisRequest) String() string { return proto.CompactTextString(m) }
func (*AnalysisRequest) ProtoMessage()    {}
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_c9e34ee2d7021e10, []int{0}
}
func (m *AnalysisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalysisRequest.Unmarshal(m, b)
}
func (m *AnalysisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalysisRequest.Marshal(b, m, deterministic)
}
func (dst *AnalysisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalysisRequest.Merge(dst, src)
}
func (m *AnalysisRequest) XXX_Size() int {
	return xxx_messageInfo_AnalysisRequest.Size(m)
}
func (m *AnalysisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalysisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnalysisRequest proto.InternalMessageInfo

func (m *AnalysisRequest) GetBeforeChange() *AnalysisTarget {
	if m != nil {
		return m.BeforeChange
	}
	return nil
}

func (m *AnalysisRequest) GetAfterChange() *AnalysisTarget {
	if m != nil {
		return m.AfterChange
	}
	return nil
}

func (m *AnalysisRequest) GetDiffsLogPath() string {
	if m != nil {
		return m.DiffsLogPath
	}
	return ""
}

type AnalysisResponse struct {
	Status               int32            `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StructureReport      *StructureReport `protobuf:"bytes,3,opt,name=structure_report,json=structureReport,proto3" json:"structure_report,omitempty"`
	SemanticsReport      *SemanticsReport `protobuf:"bytes,4,opt,name=semantics_report,json=semanticsReport,proto3" json:"semantics_report,omitempty"`
	AbstractReport       *AbstractReport  `protobuf:"bytes,5,opt,name=abstract_report,json=abstractReport,proto3" json:"abstract_report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AnalysisResponse) Reset()         { *m = AnalysisResponse{} }
func (m *AnalysisResponse) String() string { return proto.CompactTextString(m) }
func (*AnalysisResponse) ProtoMessage()    {}
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_c9e34ee2d7021e10, []int{1}
}
func (m *AnalysisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalysisResponse.Unmarshal(m, b)
}
func (m *AnalysisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalysisResponse.Marshal(b, m, deterministic)
}
func (dst *AnalysisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalysisResponse.Merge(dst, src)
}
func (m *AnalysisResponse) XXX_Size() int {
	return xxx_messageInfo_AnalysisResponse.Size(m)
}
func (m *AnalysisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalysisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnalysisResponse proto.InternalMessageInfo

func (m *AnalysisResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AnalysisResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AnalysisResponse) GetStructureReport() *StructureReport {
	if m != nil {
		return m.StructureReport
	}
	return nil
}

func (m *AnalysisResponse) GetSemanticsReport() *SemanticsReport {
	if m != nil {
		return m.SemanticsReport
	}
	return nil
}

func (m *AnalysisResponse) GetAbstractReport() *AbstractReport {
	if m != nil {
		return m.AbstractReport
	}
	return nil
}

type AnalysisTarget struct {
	RepoPath             string   `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	FilePath             string   `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalysisTarget) Reset()         { *m = AnalysisTarget{} }
func (m *AnalysisTarget) String() string { return proto.CompactTextString(m) }
func (*AnalysisTarget) ProtoMessage()    {}
func (*AnalysisTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_c9e34ee2d7021e10, []int{2}
}
func (m *AnalysisTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalysisTarget.Unmarshal(m, b)
}
func (m *AnalysisTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalysisTarget.Marshal(b, m, deterministic)
}
func (dst *AnalysisTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalysisTarget.Merge(dst, src)
}
func (m *AnalysisTarget) XXX_Size() int {
	return xxx_messageInfo_AnalysisTarget.Size(m)
}
func (m *AnalysisTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalysisTarget.DiscardUnknown(m)
}

var xxx_messageInfo_AnalysisTarget proto.InternalMessageInfo

func (m *AnalysisTarget) GetRepoPath() string {
	if m != nil {
		return m.RepoPath
	}
	return ""
}

func (m *AnalysisTarget) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type StructureReport struct {
	AstBeforePath          string   `protobuf:"bytes,1,opt,name=ast_before_path,json=astBeforePath,proto3" json:"ast_before_path,omitempty"`
	AstAfterPath           string   `protobuf:"bytes,2,opt,name=ast_after_path,json=astAfterPath,proto3" json:"ast_after_path,omitempty"`
	CfgBeforePath          string   `protobuf:"bytes,3,opt,name=cfg_before_path,json=cfgBeforePath,proto3" json:"cfg_before_path,omitempty"`
	CfgAfterPath           string   `protobuf:"bytes,4,opt,name=cfg_after_path,json=cfgAfterPath,proto3" json:"cfg_after_path,omitempty"`
	AstEdgeListsBeforePath string   `protobuf:"bytes,5,opt,name=ast_edge_lists_before_path,json=astEdgeListsBeforePath,proto3" json:"ast_edge_lists_before_path,omitempty"`
	AstEdgeListsAfterPath  string   `protobuf:"bytes,6,opt,name=ast_edge_lists_after_path,json=astEdgeListsAfterPath,proto3" json:"ast_edge_lists_after_path,omitempty"`
	CfgEdgeListsBeforePath string   `protobuf:"bytes,7,opt,name=cfg_edge_lists_before_path,json=cfgEdgeListsBeforePath,proto3" json:"cfg_edge_lists_before_path,omitempty"`
	CfgEdgeListsAfterPath  string   `protobuf:"bytes,8,opt,name=cfg_edge_lists_after_path,json=cfgEdgeListsAfterPath,proto3" json:"cfg_edge_lists_after_path,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *StructureReport) Reset()         { *m = StructureReport{} }
func (m *StructureReport) String() string { return proto.CompactTextString(m) }
func (*StructureReport) ProtoMessage()    {}
func (*StructureReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_c9e34ee2d7021e10, []int{3}
}
func (m *StructureReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructureReport.Unmarshal(m, b)
}
func (m *StructureReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructureReport.Marshal(b, m, deterministic)
}
func (dst *StructureReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructureReport.Merge(dst, src)
}
func (m *StructureReport) XXX_Size() int {
	return xxx_messageInfo_StructureReport.Size(m)
}
func (m *StructureReport) XXX_DiscardUnknown() {
	xxx_messageInfo_StructureReport.DiscardUnknown(m)
}

var xxx_messageInfo_StructureReport proto.InternalMessageInfo

func (m *StructureReport) GetAstBeforePath() string {
	if m != nil {
		return m.AstBeforePath
	}
	return ""
}

func (m *StructureReport) GetAstAfterPath() string {
	if m != nil {
		return m.AstAfterPath
	}
	return ""
}

func (m *StructureReport) GetCfgBeforePath() string {
	if m != nil {
		return m.CfgBeforePath
	}
	return ""
}

func (m *StructureReport) GetCfgAfterPath() string {
	if m != nil {
		return m.CfgAfterPath
	}
	return ""
}

func (m *StructureReport) GetAstEdgeListsBeforePath() string {
	if m != nil {
		return m.AstEdgeListsBeforePath
	}
	return ""
}

func (m *StructureReport) GetAstEdgeListsAfterPath() string {
	if m != nil {
		return m.AstEdgeListsAfterPath
	}
	return ""
}

func (m *StructureReport) GetCfgEdgeListsBeforePath() string {
	if m != nil {
		return m.CfgEdgeListsBeforePath
	}
	return ""
}

func (m *StructureReport) GetCfgEdgeListsAfterPath() string {
	if m != nil {
		return m.CfgEdgeListsAfterPath
	}
	return ""
}

type SemanticsReport struct {
	SsgBeforePath          string   `protobuf:"bytes,1,opt,name=ssg_before_path,json=ssgBeforePath,proto3" json:"ssg_before_path,omitempty"`
	SsgAfterPath           string   `protobuf:"bytes,2,opt,name=ssg_after_path,json=ssgAfterPath,proto3" json:"ssg_after_path,omitempty"`
	SsgEdgeListsBeforePath string   `protobuf:"bytes,3,opt,name=ssg_edge_lists_before_path,json=ssgEdgeListsBeforePath,proto3" json:"ssg_edge_lists_before_path,omitempty"`
	SsgEdgeListsAfterPath  string   `protobuf:"bytes,4,opt,name=ssg_edge_lists_after_path,json=ssgEdgeListsAfterPath,proto3" json:"ssg_edge_lists_after_path,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *SemanticsReport) Reset()         { *m = SemanticsReport{} }
func (m *SemanticsReport) String() string { return proto.CompactTextString(m) }
func (*SemanticsReport) ProtoMessage()    {}
func (*SemanticsReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_c9e34ee2d7021e10, []int{4}
}
func (m *SemanticsReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SemanticsReport.Unmarshal(m, b)
}
func (m *SemanticsReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SemanticsReport.Marshal(b, m, deterministic)
}
func (dst *SemanticsReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SemanticsReport.Merge(dst, src)
}
func (m *SemanticsReport) XXX_Size() int {
	return xxx_messageInfo_SemanticsReport.Size(m)
}
func (m *SemanticsReport) XXX_DiscardUnknown() {
	xxx_messageInfo_SemanticsReport.DiscardUnknown(m)
}

var xxx_messageInfo_SemanticsReport proto.InternalMessageInfo

func (m *SemanticsReport) GetSsgBeforePath() string {
	if m != nil {
		return m.SsgBeforePath
	}
	return ""
}

func (m *SemanticsReport) GetSsgAfterPath() string {
	if m != nil {
		return m.SsgAfterPath
	}
	return ""
}

func (m *SemanticsReport) GetSsgEdgeListsBeforePath() string {
	if m != nil {
		return m.SsgEdgeListsBeforePath
	}
	return ""
}

func (m *SemanticsReport) GetSsgEdgeListsAfterPath() string {
	if m != nil {
		return m.SsgEdgeListsAfterPath
	}
	return ""
}

type AbstractReport struct {
	MetaCommitPath       string   `protobuf:"bytes,1,opt,name=meta_commit_path,json=metaCommitPath,proto3" json:"meta_commit_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AbstractReport) Reset()         { *m = AbstractReport{} }
func (m *AbstractReport) String() string { return proto.CompactTextString(m) }
func (*AbstractReport) ProtoMessage()    {}
func (*AbstractReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_c9e34ee2d7021e10, []int{5}
}
func (m *AbstractReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AbstractReport.Unmarshal(m, b)
}
func (m *AbstractReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AbstractReport.Marshal(b, m, deterministic)
}
func (dst *AbstractReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AbstractReport.Merge(dst, src)
}
func (m *AbstractReport) XXX_Size() int {
	return xxx_messageInfo_AbstractReport.Size(m)
}
func (m *AbstractReport) XXX_DiscardUnknown() {
	xxx_messageInfo_AbstractReport.DiscardUnknown(m)
}

var xxx_messageInfo_AbstractReport proto.InternalMessageInfo

func (m *AbstractReport) GetMetaCommitPath() string {
	if m != nil {
		return m.MetaCommitPath
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_c9e34ee2d7021e10, []int{6}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AnalysisRequest)(nil), "analyzer.AnalysisRequest")
	proto.RegisterType((*AnalysisResponse)(nil), "analyzer.AnalysisResponse")
	proto.RegisterType((*AnalysisTarget)(nil), "analyzer.AnalysisTarget")
	proto.RegisterType((*StructureReport)(nil), "analyzer.StructureReport")
	proto.RegisterType((*SemanticsReport)(nil), "analyzer.SemanticsReport")
	proto.RegisterType((*AbstractReport)(nil), "analyzer.AbstractReport")
	proto.RegisterType((*Empty)(nil), "analyzer.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnalysisClient is the client API for Analysis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnalysisClient interface {
	GetReports(ctx context.Context, in *AnalysisRequest, opts ...grpc.CallOption) (*AnalysisResponse, error)
	GetStructureReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetSemanticReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetAbstractReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type analysisClient struct {
	cc *grpc.ClientConn
}

func NewAnalysisClient(cc *grpc.ClientConn) AnalysisClient {
	return &analysisClient{cc}
}

func (c *analysisClient) GetReports(ctx context.Context, in *AnalysisRequest, opts ...grpc.CallOption) (*AnalysisResponse, error) {
	out := new(AnalysisResponse)
	err := c.cc.Invoke(ctx, "/analyzer.Analysis/GetReports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisClient) GetStructureReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/analyzer.Analysis/GetStructureReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisClient) GetSemanticReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/analyzer.Analysis/GetSemanticReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisClient) GetAbstractReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/analyzer.Analysis/GetAbstractReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisServer is the server API for Analysis service.
type AnalysisServer interface {
	GetReports(context.Context, *AnalysisRequest) (*AnalysisResponse, error)
	GetStructureReport(context.Context, *Empty) (*Empty, error)
	GetSemanticReport(context.Context, *Empty) (*Empty, error)
	GetAbstractReport(context.Context, *Empty) (*Empty, error)
}

func RegisterAnalysisServer(s *grpc.Server, srv AnalysisServer) {
	s.RegisterService(&_Analysis_serviceDesc, srv)
}

func _Analysis_GetReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServer).GetReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/analyzer.Analysis/GetReports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServer).GetReports(ctx, req.(*AnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analysis_GetStructureReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServer).GetStructureReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/analyzer.Analysis/GetStructureReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServer).GetStructureReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analysis_GetSemanticReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServer).GetSemanticReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/analyzer.Analysis/GetSemanticReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServer).GetSemanticReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analysis_GetAbstractReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServer).GetAbstractReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/analyzer.Analysis/GetAbstractReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServer).GetAbstractReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Analysis_serviceDesc = grpc.ServiceDesc{
	ServiceName: "analyzer.Analysis",
	HandlerType: (*AnalysisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReports",
			Handler:    _Analysis_GetReports_Handler,
		},
		{
			MethodName: "GetStructureReport",
			Handler:    _Analysis_GetStructureReport_Handler,
		},
		{
			MethodName: "GetSemanticReport",
			Handler:    _Analysis_GetSemanticReport_Handler,
		},
		{
			MethodName: "GetAbstractReport",
			Handler:    _Analysis_GetAbstractReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/analyzer/reporter.proto",
}

func init() {
	proto.RegisterFile("protos/analyzer/reporter.proto", fileDescriptor_reporter_c9e34ee2d7021e10)
}

var fileDescriptor_reporter_c9e34ee2d7021e10 = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0x96, 0x93, 0x10, 0x60, 0x00, 0x9b, 0xae, 0x14, 0x04, 0xb4, 0xaa, 0x22, 0x14, 0x45, 0x9c,
	0x88, 0x44, 0xd5, 0xaa, 0x4a, 0xd4, 0x03, 0xa1, 0x51, 0xa4, 0x2a, 0x87, 0xca, 0xed, 0xa9, 0x17,
	0x6b, 0x31, 0x6b, 0x63, 0x09, 0x63, 0xea, 0x19, 0x0e, 0xe9, 0x6b, 0xf4, 0xd4, 0xe7, 0xe8, 0xb3,
	0xf4, 0x51, 0x7a, 0xaf, 0x76, 0xd7, 0x0b, 0xb6, 0x09, 0x8a, 0x7a, 0xf3, 0xce, 0x7c, 0x3f, 0xbb,
	0xdf, 0xac, 0x17, 0x5e, 0xaf, 0xd3, 0x84, 0x12, 0xbc, 0xe2, 0x2b, 0xbe, 0x7c, 0xfc, 0x21, 0xd2,
	0xab, 0x54, 0xac, 0x93, 0x94, 0x44, 0x3a, 0x52, 0x0d, 0x56, 0x33, 0x8d, 0xc1, 0x6f, 0x0b, 0x9c,
	0x89, 0x5c, 0x60, 0x84, 0xae, 0xf8, 0xbe, 0x11, 0x48, 0xec, 0x03, 0xb4, 0x66, 0x22, 0x48, 0x52,
	0xe1, 0xf9, 0x0b, 0xbe, 0x0a, 0x45, 0xd7, 0x3a, 0xb7, 0x86, 0x8d, 0x71, 0x77, 0x64, 0x58, 0x23,
	0xc3, 0xf8, 0xca, 0xd3, 0x50, 0x90, 0xdb, 0xd4, 0xf0, 0xa9, 0x42, 0xb3, 0x1b, 0x68, 0xf2, 0x80,
	0x44, 0x6a, 0xd8, 0x47, 0xcf, 0xb0, 0x1b, 0x0a, 0x9d, 0x91, 0x2f, 0xc0, 0x9e, 0x47, 0x41, 0x80,
	0xde, 0x32, 0x09, 0xbd, 0x35, 0xa7, 0x45, 0xf7, 0xf8, 0xdc, 0x1a, 0xd6, 0xdd, 0xa6, 0xaa, 0x3e,
	0x24, 0xe1, 0x67, 0x4e, 0x8b, 0xc1, 0xcf, 0x23, 0x68, 0xef, 0x76, 0x8d, 0xeb, 0x64, 0x85, 0x82,
	0x75, 0xe0, 0x14, 0x89, 0xd3, 0x06, 0xd5, 0x7e, 0x2b, 0x6e, 0xb6, 0x62, 0x5d, 0xa8, 0xc6, 0x02,
	0x91, 0x67, 0x5b, 0xa9, 0xbb, 0x66, 0xc9, 0x3e, 0x42, 0x1b, 0x29, 0xdd, 0xf8, 0xb4, 0x49, 0x85,
	0xa7, 0x23, 0x52, 0x76, 0x8d, 0x71, 0x6f, 0xb7, 0xdb, 0x2f, 0x06, 0xe1, 0x2a, 0x80, 0xeb, 0x60,
	0xb1, 0xa0, 0x54, 0x44, 0xcc, 0x57, 0x14, 0xf9, 0x68, 0x54, 0x4e, 0xf6, 0x54, 0x0c, 0x62, 0xab,
	0x52, 0x2c, 0xb0, 0x09, 0x38, 0x7c, 0x86, 0x94, 0x72, 0x9f, 0x8c, 0x48, 0x65, 0x2f, 0xb8, 0x0c,
	0x90, 0x69, 0xd8, 0xbc, 0xb0, 0x1e, 0x7c, 0x02, 0xbb, 0x18, 0x2d, 0x7b, 0x09, 0x75, 0xa9, 0xa5,
	0x83, 0xb4, 0xd4, 0xe1, 0x6b, 0xb2, 0x20, 0x43, 0x94, 0xcd, 0x20, 0x5a, 0x0a, 0xdd, 0xd4, 0xc9,
	0xd4, 0x64, 0x41, 0x25, 0xfc, 0xeb, 0x18, 0x9c, 0xd2, 0xc9, 0xd9, 0x25, 0x38, 0x1c, 0xc9, 0xcb,
	0xee, 0x46, 0x4e, 0xb3, 0xc5, 0x91, 0x6e, 0x55, 0x55, 0x09, 0x5f, 0x80, 0x2d, 0x71, 0xfa, 0x12,
	0xe4, 0xd4, 0x9b, 0x1c, 0x69, 0x22, 0x8b, 0x0a, 0x75, 0x09, 0x8e, 0x1f, 0x84, 0x05, 0x35, 0x3d,
	0xea, 0x96, 0x1f, 0x84, 0x45, 0x35, 0x89, 0xcb, 0xa9, 0x9d, 0x68, 0x35, 0x3f, 0x08, 0x77, 0x6a,
	0xd7, 0xd0, 0x97, 0x9e, 0x62, 0x1e, 0x0a, 0x6f, 0x19, 0x21, 0x61, 0x41, 0xb8, 0xa2, 0x18, 0x1d,
	0x8e, 0x74, 0x37, 0x0f, 0xc5, 0x83, 0xec, 0xe7, 0x1c, 0xde, 0x43, 0xaf, 0xc4, 0xcd, 0x99, 0x9d,
	0x2a, 0xea, 0x59, 0x9e, 0x5a, 0x70, 0x95, 0x7b, 0x3b, 0xe0, 0x5a, 0xd5, 0xae, 0x7e, 0x10, 0x1e,
	0x70, 0x2d, 0x71, 0x73, 0xae, 0x35, 0xed, 0x9a, 0xa7, 0x6e, 0x5d, 0x07, 0x7f, 0x2c, 0x70, 0x4a,
	0xf7, 0x49, 0xa6, 0x89, 0x18, 0x3e, 0x35, 0x1b, 0xc4, 0x52, 0x9a, 0x12, 0xb7, 0x3f, 0x1b, 0xc4,
	0x62, 0x9a, 0x12, 0x75, 0xe0, 0x5c, 0x7a, 0x4c, 0x1d, 0xc4, 0x43, 0xe7, 0x2a, 0x71, 0xf7, 0x46,
	0x77, 0x96, 0xa7, 0xee, 0xce, 0x75, 0x0d, 0x76, 0xf1, 0x86, 0xb3, 0x21, 0xb4, 0x63, 0x41, 0xdc,
	0xf3, 0x93, 0x38, 0x8e, 0x28, 0x7f, 0x2c, 0x5b, 0xd6, 0xa7, 0xaa, 0xac, 0xb8, 0x55, 0xa8, 0xdc,
	0xc5, 0x6b, 0x7a, 0x1c, 0xff, 0xb5, 0xa0, 0x66, 0xfe, 0x02, 0x36, 0x05, 0xb8, 0x17, 0x99, 0x18,
	0xb2, 0xde, 0xfe, 0x13, 0x94, 0x3d, 0x79, 0xfd, 0xfe, 0x53, 0xad, 0xec, 0x5d, 0x79, 0x07, 0xec,
	0x5e, 0x50, 0xf9, 0x67, 0x70, 0x76, 0x0c, 0x65, 0xdc, 0x2f, 0x17, 0xd8, 0x5b, 0x78, 0x21, 0x79,
	0xd9, 0xa0, 0xfe, 0x93, 0x56, 0x0a, 0xe2, 0x59, 0xda, 0xed, 0xab, 0x6f, 0x7d, 0xf5, 0xb6, 0xcf,
	0x36, 0xc1, 0xf6, 0xd9, 0xbf, 0x31, 0x1f, 0xb3, 0x53, 0xd5, 0x7b, 0xf3, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0xe6, 0x7f, 0xb4, 0x38, 0x19, 0x06, 0x00, 0x00,
}
