// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/analyzer/bytecode_analyzer.proto

package analyzer // import "protobuf/analyzer"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ByteCodeAnalysisRequest struct {
	BeforeChange         *AnalysisTarget `protobuf:"bytes,1,opt,name=before_change,json=beforeChange,proto3" json:"before_change,omitempty"`
	AfterChange          *AnalysisTarget `protobuf:"bytes,2,opt,name=after_change,json=afterChange,proto3" json:"after_change,omitempty"`
	DiffsLogPath         string          `protobuf:"bytes,3,opt,name=diffs_log_path,json=diffsLogPath,proto3" json:"diffs_log_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ByteCodeAnalysisRequest) Reset()         { *m = ByteCodeAnalysisRequest{} }
func (m *ByteCodeAnalysisRequest) String() string { return proto.CompactTextString(m) }
func (*ByteCodeAnalysisRequest) ProtoMessage()    {}
func (*ByteCodeAnalysisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bytecode_analyzer_3176fe293ce2fa7c, []int{0}
}
func (m *ByteCodeAnalysisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByteCodeAnalysisRequest.Unmarshal(m, b)
}
func (m *ByteCodeAnalysisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByteCodeAnalysisRequest.Marshal(b, m, deterministic)
}
func (dst *ByteCodeAnalysisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByteCodeAnalysisRequest.Merge(dst, src)
}
func (m *ByteCodeAnalysisRequest) XXX_Size() int {
	return xxx_messageInfo_ByteCodeAnalysisRequest.Size(m)
}
func (m *ByteCodeAnalysisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByteCodeAnalysisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByteCodeAnalysisRequest proto.InternalMessageInfo

func (m *ByteCodeAnalysisRequest) GetBeforeChange() *AnalysisTarget {
	if m != nil {
		return m.BeforeChange
	}
	return nil
}

func (m *ByteCodeAnalysisRequest) GetAfterChange() *AnalysisTarget {
	if m != nil {
		return m.AfterChange
	}
	return nil
}

func (m *ByteCodeAnalysisRequest) GetDiffsLogPath() string {
	if m != nil {
		return m.DiffsLogPath
	}
	return ""
}

type ByteCodeAnalysisResponse struct {
	Status                 int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message                string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CfgBeforePath          string   `protobuf:"bytes,3,opt,name=cfg_before_path,json=cfgBeforePath,proto3" json:"cfg_before_path,omitempty"`
	CfgAfterPath           string   `protobuf:"bytes,4,opt,name=cfg_after_path,json=cfgAfterPath,proto3" json:"cfg_after_path,omitempty"`
	SsgBeforePath          string   `protobuf:"bytes,5,opt,name=ssg_before_path,json=ssgBeforePath,proto3" json:"ssg_before_path,omitempty"`
	SsgAfterPath           string   `protobuf:"bytes,6,opt,name=ssg_after_path,json=ssgAfterPath,proto3" json:"ssg_after_path,omitempty"`
	CfgAbstractPath        string   `protobuf:"bytes,7,opt,name=cfg_abstract_path,json=cfgAbstractPath,proto3" json:"cfg_abstract_path,omitempty"`
	SsgAbstractPath        string   `protobuf:"bytes,8,opt,name=ssg_abstract_path,json=ssgAbstractPath,proto3" json:"ssg_abstract_path,omitempty"`
	CfgEdgeListsBeforePath string   `protobuf:"bytes,9,opt,name=cfg_edge_lists_before_path,json=cfgEdgeListsBeforePath,proto3" json:"cfg_edge_lists_before_path,omitempty"`
	CfgEdgeListsAfterPath  string   `protobuf:"bytes,10,opt,name=cfg_edge_lists_after_path,json=cfgEdgeListsAfterPath,proto3" json:"cfg_edge_lists_after_path,omitempty"`
	SsgEdgeListsBeforePath string   `protobuf:"bytes,11,opt,name=ssg_edge_lists_before_path,json=ssgEdgeListsBeforePath,proto3" json:"ssg_edge_lists_before_path,omitempty"`
	SsgEdgeListsAfterPath  string   `protobuf:"bytes,12,opt,name=ssg_edge_lists_after_path,json=ssgEdgeListsAfterPath,proto3" json:"ssg_edge_lists_after_path,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ByteCodeAnalysisResponse) Reset()         { *m = ByteCodeAnalysisResponse{} }
func (m *ByteCodeAnalysisResponse) String() string { return proto.CompactTextString(m) }
func (*ByteCodeAnalysisResponse) ProtoMessage()    {}
func (*ByteCodeAnalysisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bytecode_analyzer_3176fe293ce2fa7c, []int{1}
}
func (m *ByteCodeAnalysisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByteCodeAnalysisResponse.Unmarshal(m, b)
}
func (m *ByteCodeAnalysisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByteCodeAnalysisResponse.Marshal(b, m, deterministic)
}
func (dst *ByteCodeAnalysisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByteCodeAnalysisResponse.Merge(dst, src)
}
func (m *ByteCodeAnalysisResponse) XXX_Size() int {
	return xxx_messageInfo_ByteCodeAnalysisResponse.Size(m)
}
func (m *ByteCodeAnalysisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ByteCodeAnalysisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ByteCodeAnalysisResponse proto.InternalMessageInfo

func (m *ByteCodeAnalysisResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ByteCodeAnalysisResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ByteCodeAnalysisResponse) GetCfgBeforePath() string {
	if m != nil {
		return m.CfgBeforePath
	}
	return ""
}

func (m *ByteCodeAnalysisResponse) GetCfgAfterPath() string {
	if m != nil {
		return m.CfgAfterPath
	}
	return ""
}

func (m *ByteCodeAnalysisResponse) GetSsgBeforePath() string {
	if m != nil {
		return m.SsgBeforePath
	}
	return ""
}

func (m *ByteCodeAnalysisResponse) GetSsgAfterPath() string {
	if m != nil {
		return m.SsgAfterPath
	}
	return ""
}

func (m *ByteCodeAnalysisResponse) GetCfgAbstractPath() string {
	if m != nil {
		return m.CfgAbstractPath
	}
	return ""
}

func (m *ByteCodeAnalysisResponse) GetSsgAbstractPath() string {
	if m != nil {
		return m.SsgAbstractPath
	}
	return ""
}

func (m *ByteCodeAnalysisResponse) GetCfgEdgeListsBeforePath() string {
	if m != nil {
		return m.CfgEdgeListsBeforePath
	}
	return ""
}

func (m *ByteCodeAnalysisResponse) GetCfgEdgeListsAfterPath() string {
	if m != nil {
		return m.CfgEdgeListsAfterPath
	}
	return ""
}

func (m *ByteCodeAnalysisResponse) GetSsgEdgeListsBeforePath() string {
	if m != nil {
		return m.SsgEdgeListsBeforePath
	}
	return ""
}

func (m *ByteCodeAnalysisResponse) GetSsgEdgeListsAfterPath() string {
	if m != nil {
		return m.SsgEdgeListsAfterPath
	}
	return ""
}

func init() {
	proto.RegisterType((*ByteCodeAnalysisRequest)(nil), "analyzer.ByteCodeAnalysisRequest")
	proto.RegisterType((*ByteCodeAnalysisResponse)(nil), "analyzer.ByteCodeAnalysisResponse")
}

func init() {
	proto.RegisterFile("protos/analyzer/bytecode_analyzer.proto", fileDescriptor_bytecode_analyzer_3176fe293ce2fa7c)
}

var fileDescriptor_bytecode_analyzer_3176fe293ce2fa7c = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x4d, 0xcf, 0xd2, 0x40,
	0x10, 0xc7, 0x53, 0x7d, 0x78, 0x5b, 0x8a, 0xc4, 0x26, 0x62, 0x6d, 0x8c, 0x21, 0xc4, 0x20, 0xf1,
	0x00, 0x89, 0x5e, 0x0c, 0xc4, 0x03, 0x10, 0x6f, 0x1c, 0x4c, 0xe3, 0xc9, 0x4b, 0xb3, 0x6d, 0x67,
	0x17, 0x12, 0x64, 0xeb, 0xce, 0x72, 0xc0, 0xcf, 0xe4, 0x37, 0xf0, 0xcb, 0x99, 0xdd, 0xed, 0xe2,
	0x52, 0x43, 0x9e, 0x1b, 0x33, 0xfb, 0xfb, 0xbf, 0x4c, 0x42, 0xc9, 0xbb, 0x4a, 0x0a, 0x25, 0x70,
	0x41, 0x4f, 0xf4, 0x78, 0xf9, 0x05, 0x72, 0x91, 0x5f, 0x14, 0x14, 0xa2, 0x84, 0xcc, 0x6d, 0xe6,
	0x86, 0x88, 0xba, 0x6e, 0x4e, 0xde, 0x34, 0x25, 0x12, 0x2a, 0x21, 0x95, 0x23, 0x27, 0x7f, 0x02,
	0xf2, 0x72, 0x73, 0x51, 0xb0, 0x15, 0x25, 0xac, 0x35, 0x83, 0x07, 0x4c, 0xe1, 0xe7, 0x19, 0x50,
	0x45, 0x9f, 0xc9, 0x20, 0x07, 0x26, 0x24, 0x64, 0xc5, 0x9e, 0x9e, 0x38, 0xc4, 0xc1, 0x38, 0x98,
	0xf5, 0x3f, 0xc4, 0xf3, 0x6b, 0x9a, 0x53, 0x7c, 0xa3, 0x92, 0x83, 0x4a, 0x43, 0x8b, 0x6f, 0x0d,
	0x1d, 0xad, 0x48, 0x48, 0x99, 0x02, 0xe9, 0xd4, 0x4f, 0x1e, 0x51, 0xf7, 0x0d, 0x5d, 0x8b, 0xdf,
	0x92, 0x67, 0xe5, 0x81, 0x31, 0xcc, 0x8e, 0x82, 0x67, 0x15, 0x55, 0xfb, 0xf8, 0xe9, 0x38, 0x98,
	0xf5, 0xd2, 0xd0, 0x6c, 0x77, 0x82, 0x7f, 0xa5, 0x6a, 0x3f, 0xf9, 0xfd, 0x40, 0xe2, 0xff, 0xdb,
	0x63, 0x25, 0x4e, 0x08, 0xd1, 0x88, 0xb4, 0x51, 0x51, 0x75, 0x46, 0xd3, 0xbb, 0x95, 0xd6, 0x53,
	0x14, 0x93, 0xce, 0x0f, 0x40, 0xa4, 0x75, 0xa5, 0x5e, 0xea, 0xc6, 0x68, 0x4a, 0x86, 0x05, 0xe3,
	0x59, 0x7d, 0xb4, 0x97, 0x3a, 0x28, 0x18, 0xdf, 0x98, 0xad, 0x8e, 0xd5, 0xe5, 0x34, 0x67, 0xaf,
	0x33, 0xd8, 0x83, 0x2d, 0x57, 0x30, 0xbe, 0xd6, 0x4b, 0x43, 0x4d, 0xc9, 0x10, 0xf1, 0xd6, 0xad,
	0x65, 0xdd, 0x10, 0x1b, 0x6e, 0x9a, 0xf3, 0xdc, 0xda, 0xd6, 0x0d, 0xd1, 0x73, 0x7b, 0x4f, 0x9e,
	0x9b, 0xcc, 0x1c, 0x95, 0xa4, 0x85, 0xb2, 0x60, 0xc7, 0x80, 0xba, 0xf4, 0xba, 0xde, 0x3b, 0xd6,
	0x38, 0xde, 0xb0, 0x5d, 0xcb, 0x6a, 0x53, 0x9f, 0x5d, 0x92, 0x44, 0xfb, 0x42, 0xc9, 0x21, 0x3b,
	0x1e, 0x50, 0xe1, 0x4d, 0xe1, 0x9e, 0x11, 0x8d, 0x0a, 0xc6, 0xbf, 0x94, 0x1c, 0x76, 0xfa, 0xdd,
	0x6b, 0xfe, 0x89, 0xbc, 0x6a, 0x68, 0xbd, 0x23, 0x88, 0x91, 0xbe, 0xf0, 0xa5, 0xff, 0xae, 0x59,
	0x92, 0x44, 0x37, 0xbc, 0x93, 0xda, 0xb7, 0xa9, 0x88, 0xf7, 0x52, 0x1b, 0x5a, 0x2f, 0x35, 0xb4,
	0xa9, 0xbe, 0xf4, 0x9a, 0xba, 0x79, 0xfd, 0x3d, 0x31, 0xff, 0xfa, 0xfc, 0xcc, 0xae, 0x1f, 0xc4,
	0xca, 0xfd, 0xc8, 0xdb, 0xe6, 0xed, 0xe3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x6b, 0x0f,
	0x8d, 0x66, 0x03, 0x00, 0x00,
}
