# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/analyzer/solidity_analyzer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.analyzer import source_code_analyzer_pb2 as protos_dot_analyzer_dot_source__code__analyzer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/analyzer/solidity_analyzer.proto',
  package='analyzer',
  syntax='proto3',
  serialized_options=b'Z\032protobuf/analyzer;analyzer',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'protos/analyzer/solidity_analyzer.proto\x12\x08\x61nalyzer\x1a*protos/analyzer/source_code_analyzer.proto2|\n\x1aSoliditySourceCodeAnalysis\x12^\n\x11\x41nalyseSourceCode\x12#.analyzer.SourceCodeAnalysisRequest\x1a$.analyzer.SourceCodeAnalysisResponseB\x1cZ\x1aprotobuf/analyzer;analyzerb\x06proto3'
  ,
  dependencies=[protos_dot_analyzer_dot_source__code__analyzer__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_SOLIDITYSOURCECODEANALYSIS = _descriptor.ServiceDescriptor(
  name='SoliditySourceCodeAnalysis',
  full_name='analyzer.SoliditySourceCodeAnalysis',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=97,
  serialized_end=221,
  methods=[
  _descriptor.MethodDescriptor(
    name='AnalyseSourceCode',
    full_name='analyzer.SoliditySourceCodeAnalysis.AnalyseSourceCode',
    index=0,
    containing_service=None,
    input_type=protos_dot_analyzer_dot_source__code__analyzer__pb2._SOURCECODEANALYSISREQUEST,
    output_type=protos_dot_analyzer_dot_source__code__analyzer__pb2._SOURCECODEANALYSISRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOLIDITYSOURCECODEANALYSIS)

DESCRIPTOR.services_by_name['SoliditySourceCodeAnalysis'] = _SOLIDITYSOURCECODEANALYSIS

# @@protoc_insertion_point(module_scope)
