dest_path: /reports
input_path: /repos
timeout: 200
listen_address: 0.0.0.0:50055
debug: false
compilation:
  Dapp-Learning:
    prepare:
      - "npm install @openzeppelin/contracts"
    compilation_base:
      remap:
        "@openzeppelin": ./node_modules/@openzeppelin
      allow_paths:
        - node_module/@openzeppelin


